# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats:
  - epub
  - pdf

conda:
  environment: environment-dev.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - pip install git+https://github.com/SAR-ARD/S1_NRB.git

sphinx:
  builder: html
  configuration: docs/conf.py
