name: nrb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal>=3.4.1
  - click
  - lxml
  - pip
  - pystac
  - scipy
  - pip:
    - spatialist @ git+https://github.com/johntruckenbrodt/spatialist.git
    - pyroSAR @ git+https://github.com/SAR-ARD/pyroSAR.git
