name: nrb_env_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - gdal>=3.5.0
  - click
  - lxml
  - pystac
  - scipy
  - sphinx<=6.2.1
  - sphinxcontrib-bibtex>=2.2
  - nbsphinx
  - sphinx_rtd_theme
  - pyroSAR>=0.19.0
  - rsgislib
  - pyproj
  - shapely
  - spatialist>=0.12.0
